### ISSUE TITLE
404 on latest blog post

### ISSUE THREAD

**Issue by pmarsceill** [jch/jch.github.io#4]
The `Making "Push on Green" a Reality` link on jch.github.io produces a 404 error:

![screenshot 2016-05-17 10 51 12](https://cloud.githubusercontent.com/assets/896475/15326843/75000398-1c1d-11e6-8c66-1bcb03a0ed11.png)

Maybe a permalink issue?

**Comment by jch** [comment]
Thanks! It was a draft post that I accidentally added to my index page. Pushed up a fix.
